-- 복식부기 원장(append-only).
-- ledger_transaction = 거래 헤더(PK가 멱등 키), journal_entry = 분개 라인.
create table ledger_transaction
(
    id          varchar(64)              not null,
    description varchar(255)             not null,
    created_at  timestamp with time zone not null,
    constraint pk_ledger_transaction primary key (id)
);

create table journal_entry
(
    id             bigint generated by default as identity,
    transaction_id varchar(64) not null,
    account_id     varchar(64) not null,
    direction      varchar(8)  not null,
    amount         bigint      not null,
    constraint pk_journal_entry primary key (id),
    constraint fk_journal_entry_transaction foreign key (transaction_id) references ledger_transaction (id),
    constraint ck_journal_entry_amount_positive check (amount > 0),
    constraint ck_journal_entry_direction check (direction in ('DEBIT', 'CREDIT'))
);

-- 계정 잔액 조회(Σ분개)를 위한 인덱스.
create index ix_journal_entry_account on journal_entry (account_id);
