-- 트랜잭셔널 아웃박스. 상태 변경과 같은 트랜잭션으로 이벤트를 적재하고, 릴레이가 발행한다.
create table outbox_event
(
    id             bigint generated by default as identity,
    aggregate_type varchar(64)              not null,
    aggregate_id   varchar(64)              not null,
    event_type     varchar(128)             not null,
    payload        text                     not null,
    created_at     timestamp with time zone not null,
    published_at   timestamp with time zone,
    constraint pk_outbox_event primary key (id)
);

-- 미발행 이벤트 조회를 빠르게 하기 위한 부분 인덱스.
create index ix_outbox_event_unpublished on outbox_event (id) where published_at is null;
