-- 개별 투자 내역. 정산 시 투자자별 분배 비율 계산에 사용된다.
create table investment
(
    id          bigint generated by default as identity,
    round_id    varchar(64) not null,
    investor_id varchar(64) not null,
    amount      bigint      not null,
    constraint pk_investment primary key (id),
    constraint ck_investment_amount_positive check (amount > 0)
);

create index ix_investment_round on investment (round_id);
