-- 상태 있는 상환 회차(스케줄). 대출 실행 시 생성되고, 정산되면 PAID, 납기 초과 시 OVERDUE.
create table loan_repayment
(
    id        bigint generated by default as identity,
    loan_id   varchar(64) not null,
    sequence  int         not null,
    due_date  date        not null,
    principal bigint      not null,
    interest  bigint      not null,
    status    varchar(16) not null,
    late_fee  bigint      not null default 0,
    constraint pk_loan_repayment primary key (id),
    constraint uq_loan_repayment unique (loan_id, sequence),
    constraint ck_loan_repayment_status check (status in ('DUE', 'PAID', 'OVERDUE'))
);

-- 연체 후보(상태=DUE, 납기 경과) 조회용.
create index ix_loan_repayment_status_due on loan_repayment (status, due_date);
